# Generated by Django 4.0.3 on 2022-03-31 09:25

from django.db import migrations, models
import forum.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_forumuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='static_root/logo/forum-logo.png', upload_to='profiles', validators=[forum.common.validators.validate_image_max_size]),
        ),
    ]
