# Generated by Django 4.0.3 on 2022-04-07 17:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.AddField(
            model_name='profile',
            name='Bio',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
