# Generated by Django 4.0.3 on 2022-04-13 20:26

from django.db import migrations, models
import forum.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='static_root/logo/forum-logo.png', null=True, upload_to='profiles', validators=[forum.common.validators.validate_image_max_size]),
        ),
    ]
