# Generated by Django 4.0.3 on 2022-04-13 20:35

from django.db import migrations, models
import forum.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='static_root/logo/forum-logo.png', upload_to='profiles', validators=[forum.common.validators.validate_image_max_size]),
        ),
    ]
