# Generated by Django 4.0.3 on 2022-04-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_likecomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeComment',
        ),
    ]
